version: '3.7'
services:
  postgres:
    volumes:
      - ${DB_DATA}:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432

  redis:
    ports:
      - ${REDIS_PORT}:6379
    depends_on:
      - postgres

  web:
    ports:
      - ${APP_PORT}:8000
    depends_on:
      - postgres

    entrypoint: ["python", "main.py"]
