version: '3.7'
services:
  postgres:
    volumes:
      - ${DB_DATA}:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    networks:
      - local_net

  redis:
    ports:
      - ${REDIS_PORT}:6379
    depends_on:
      - postgres
    networks:
      - local_net

  web:
    ports:
      - ${APP_PORT}:8000
    depends_on:
      - postgres

    entrypoint: ["python", "app/main.py"]
    networks:
      - local_net


networks:
  local_net:
    driver: bridge