"""update_user

Revision ID: a6a5db82ca53
Revises: 67d9dc5b552a
Create Date: 2022-11-07 20:17:13.814740

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a6a5db82ca53'
down_revision = '67d9dc5b552a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users', 'login',
        existing_type=sa.VARCHAR(length=128),
        nullable=False,
        schema='users'
    )
    op.alter_column(
        'users', 'email',
        existing_type=sa.VARCHAR(length=256),
        nullable=True,
        schema='users'
    )
    op.alter_column(
        'users', 'password',
        existing_type=sa.VARCHAR(length=256),
        nullable=True,
        schema='users'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users', 'password',
        existing_type=sa.VARCHAR(length=256),
        nullable=False,
        schema='users'
    )
    op.alter_column(
        'users', 'email',
        existing_type=sa.VARCHAR(length=256),
        nullable=False,
        schema='users'
    )
    op.alter_column(
        'users', 'login',
        existing_type=sa.VARCHAR(length=128),
        nullable=True,
        schema='users'
    )
    # ### end Alembic commands ###
