"""social_accounts

Revision ID: 67d9dc5b552a
Revises: f1e3c9f1923c
Create Date: 2022-11-06 12:51:14.000726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '67d9dc5b552a'
down_revision = 'f1e3c9f1923c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_social_accounts',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('social_id', sa.Text(), nullable=False),
        sa.Column('social_name', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.users.id'],
            name=op.f('fk_user_social_accounts_user_id_users'),
            ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_user_social_accounts')),
        sa.UniqueConstraint('social_id', 'social_name', name='unique_social_pk'),
        schema='users'
    )
    op.create_index(
        op.f('ix_users_user_social_accounts_user_id'),
        'user_social_accounts',
        ['user_id'],
        unique=False,
        schema='users'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_users_user_social_accounts_user_id'),
        table_name='user_social_accounts',
        schema='users'
    )
    op.drop_table('user_social_accounts', schema='users')
    # ### end Alembic commands ###
