"""additional_auth_flag

Revision ID: 5ea42feb5940
Revises: f1e3c9f1923c
Create Date: 2022-11-08 18:34:31.953015

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5ea42feb5940'
down_revision = 'f1e3c9f1923c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'is_use_additional_auth',
            sa.Boolean(),
            server_default='false',
            nullable=False,
            comment='Использовать ли двухфакторную аутентификацию'
        ),
        schema='users'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_use_additional_auth', schema='users')
    # ### end Alembic commands ###
